language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: COVERAGE=true
    - php: 7.4
  fast_finish: true
  allow_failures:
    - php: 7.4

git:
    depth: 1

services:
  - docker

addons:
  apt:
    packages:
      - rabbitmq-server

cache:
  directories:
    - $HOME/.composer
    - vendor

before_install:
  - docker pull shopify/toxiproxy
  - docker run -d --rm --net=host -p 8474:8474 -p 5673:5673 shopify/toxiproxy
  - docker ps -a
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

env:
  global:
    - TOXIPROXY_HOST=localhost TOXIPROXY_AMQP_PORT=5673

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit -d zend.enable_gc=0 --exclude-group management --coverage-text --coverage-clover=coverage.clover

after_success: >
    if [[ $COVERAGE = true ]]; then
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
